# Configuração global do Prometheus
global:
  scrape_interval: 15s  # Intervalo de coleta de métricas
  evaluation_interval: 15s  # Intervalo de avaliação de regras

# Configuração de jobs para coleta de métricas
scrape_configs:
  # Métricas da aplicação Flask
  - job_name: 'escola-app'
    static_configs:
      - targets: ['app:5000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Métricas do banco PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s

  # Métricas dos containers Docker
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 20s

  # Métricas do sistema operacional
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 30s

  # Métricas do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s